dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-11/run.sh | bash
notifications:
  slack:
    rooms:
      secure:
fCbMNmFHCjDO0mMFJYZkP5vuRDVAFCK6PzYZ1BEHjTlAFY1irWO9b2qlMU7qQQelI+Z4mFvfyqngXyC6SBFgBu9NFJZv3XeW6FNnnyeX4NVpZQism/nobomvMGmuRNQG0s0WGuSviCqqwYjQZ3e+mXSTV7LP5FGdrmNYGlmiMUkQAMba/63YKQ1ZtMKc1tRbhR3VCX9t1SNeUhZJafGXsVtJzL4ERgzlGLfxhgjtKnO2AZHFywQxWT1Wt0tegxLuLvATZd98vwGu7Sah0muCWNIqhtEHcKddcCCljlfQw6Ej81oqmdLhbfbD9VD8wMcdbnL1aPw5AV5peJq60n+8wuEvo0wkpKyCzP4DI3LmLWBEQO9eOO/J+WNttmAGlU5rwf9FDSlnooWdr80Jg31LYztgmBfG+N+OuxcGW6x7QXDOP9pQjK13Q9mc954cBAOqcf+D+wKPdWWxkwuHv0blkVlqVSJbFOAb3bthHpoFgthc8kN/LwookVUIV3q0M2aLcF3+G0Tfv/EXeGb+HDu3cGaTfdhRSTGmduRbgRTKPLrtbr8KrGU4WrE3pLSpMPKv5KfzU/iucYg4DkKSIFKDRkpHEngCMbvnwYZJpEXWjnGpmBnyyHXEzFP7bFqOy0I4mCX5Exea6UDQIh6akHqFcBcxXT0ptpf0jOvhwkKjsmk=
